Fix build error
In regular builds without DEBUG enabled, I get this build error:
```
cc -g -O2 -Werror=implicit-function-declaration -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -ffile-prefix-map=/srv/build/irmplircd-2.2.4+git20260804-39-c7aea2b=. -flto=auto -ffat-lto-objects -fstack-protector-strong -fstack-clash-protection -Wformat -Werror=format-security -fcf-protection -fdebug-prefix-map=/srv/build/irmplircd-2.2.4+git20260804-39-c7aea2b=/usr/src/irmplircd-2.2.4+git20260804-39-c7aea2b-0yavdr0~resolute -Ic_hashmap -c mapping.c
irmplircd.c: In function ‘processevent’:
irmplircd.c:213:9: error: ‘else’ without a previous ‘if’
  213 |         else
      |         ^~~~

```
The additional code block is needed to prevent the build error.